version: '3.8'
services:
  jobmatcher:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser